### ISSUE TITLE
Change entities naming in v2.0.0 leads to incompatibility with MeteoalarmCard

### ISSUE THREAD

**Issue by nepozs** [PiotrMachowski/Home-Assistant-custom-components-Burze.dzis.net#22] opened 2023-07-15 18:27 UTC
https://github.com/MrBartusek/MeteoalarmCard/issues/201
as you can see - the weather condition is selected by the name of the entity
https://github.com/MrBartusek/MeteoalarmCard/blob/master/src/integrations/burze_dzis_net.ts
so if these names are not in English, they won't work properly.
If these names will always be Polish, it will be easy to fix.

@PiotrMachowski 
So maybe this change needs your declaration if will it be persistent change.

There is also secondary problem - I don't understand idea of doubling entities:
all of
`binary_sensor.burze_dzis_net_ostrzezenie_aktywne_xxx`
are identical to
`binary_sensor.burze_dzis_net_ostrzezenie_xxx`

**Comment by PiotrMachowski** [comment] 2023-07-16 02:13
The problem is that now it's possible to change entity IDs for entities generated by this integration. I have a solution for that (I use it in my vacuum map card), I'll check if I'll be able to apply it in Meteoalarm card.
---
"Aktywne" entities mean that there is a warning and it is active at this moment (warnings have start and end times and they can be published e.g. a day before)
Normal entities are "on" whenever there is a warning, without checking the time.

**Comment by PiotrMachowski** [comment] 2023-07-16 22:02
I'll close this issue as it should be handled on the card side

**Closed by PiotrMachowski** 2023-07-16 22:02 UTC
